# Any configurations that apply only to the production environment

version: '3.8'

services:
    api:
        image: jeffstjean/enactushacks_nodejs:prod
        deploy:
            replicas: 3
            restart_policy: 
                max_attempts: 3
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
        environment:
            - NODE_ENV=PRODUCTION 
configs:
    proxy:
        file: ./nginx/prod.conf