# Any configurations that apply only to local development

version: '3'
services:
    api:
        image: jeffstjean/enactushacks_nodejs:dev
        ports:
            - "5000:5000"
        volumes:
            - ./api:/home/node/app
        deploy:
            replicas: 1
            restart_policy: 
                max_attempts: 3
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 0s
    proxy:
        image: jeffstjean/enactushacks_nginx:dev
    db:
        image: mongo:4.4.0
        ports:
            - "27017:27017"
        volumes:
            - database:/data/db
        networks:
            - app-network
        deploy:
            replicas: 1
            restart_policy: 
                max_attempts: 3
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 0s
volumes:
    database: