version: '3'
services:
  app:
    image: node:alpine
    container_name: nodejs
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:${PORT}"
    command: npm run dev
    links:
      - database
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
