version: '3'
services:
  app:
    image: node:alpine
    container_name: nodejs
    env_file: .env
    ports:
      - '${SITE_PORT}:${SITE_PORT}'
    depends_on:
      - db
    networks:
      - dev-network

  db:
    image: mongo
    container_name: mongo
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - /data/db:/data/db
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
