version: '3'
services:
  app:
    command: npm run prod
    volumes:
      - .:/app
    restart: always
    environment:
      - NODE_ENV=production

  database:
    volumes:
      - './data:/data/db'
