version: '3'
services:
  app:
    image: node:alpine
    container_name: nodejs
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    networks:
      - network

  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    networks:
      - network

networks:
  network:
    driver: bridge
